version: '3.8'
services:
  test:
    image: mslback:0.1
    volumes:
      # - ${LOCAL_LETSENCRYPT_PATH}:/Certificates
      - .:/app
      - test-volumes:/app/node_modules
    working_dir: /app
    ports:
      - "${DEFAULT}:${DEFAULT}"
    environment:
      - NODE_ENV=production
      - BACKENDPORT=${DEFAULT}
      - DATABASE=${TDATABASE}
      - REDISDB=${TREDISDB}
      - MONGO:${MONGO_TEST}
      - GOOGLECALLBACKURL:${GOOGLECALLBACKURLTEST}
      - GOOGLELOGINURL:${GOOGLELOGINURLTEST}
      - WEB_404URL:${WEB_404URL_TEST}      
      - EMAILURL:${EMAILURL_TEST}
      - EMAILSOCKET_URL:${EMAILSOCKET_URL_TEST}
      - CHECK_EMAIL:${CHECK_EMAIL_TEST}
    command: pm2-runtime start ecosystem.config.js --env production

  deploy:      
      image: mslback:0.1
      volumes:
        # - ${LOCAL_LETSENCRYPT_PATH}:/Certificates
        - .:/app
        - deploy-volumes:/app/node_modules
      working_dir: /app      
      ports:
        - "${BACKENDPORT}:${BACKENDPORT}"
      environment:
        - NODE_ENV=development
        - BACKENDPORT=${BACKENDPORT}
        - DATABASE=${DATABASE}
        - REDISDB=${REDISDB}
        - MONGO:${MONGO}
        - GOOGLECALLBACKURL:${GOOGLECALLBACKURL}
        - GOOGLELOGINURL:${GOOGLELOGINURL}
        - WEB_404URL:${WEB_404URL}
        - EMAILURL:${EMAILURL}        
        - EMAILSOCKET_URL:${EMAILSOCKET_URL}
        - CHECK_EMAIL:${CHECK_EMAIL}      
      command: pm2-runtime start ecosystem.config.js --env development

  nginx:
    image: nginx:latest
    volumes:
      - ${LOCAL_LETSENCRYPT_PATH}:/Certificates
      # - C:/Users/cho/Desktop/cert/:/Certificates
      # - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}" # 외부에서 접근할 SSL 포트
    #   - "4500:4500"   # HTTP 리다이렉트 포트
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - BACKENDPORT=${BACKENDPORT}
      - DEFAULT=${DEFAULT}
      - DOCKER_CERT=${DOCKER_CERT}
      - DOCKER_KEY=${DOCKER_KEY}
      - DOCKER_CHAIN=${DOCKER_CHAIN}
      - HOST=${REDISHOST}
      - PASSWORD=${PASSWORD}
      # '${NGINX_PORT} ${BACKENDPORT} ${DEFAULT} ${DOCKER_KEY} ${DOCKER_CHAIN} ${HOST} ${PASSWORD}'
    # command: ["/bin/sh", "-c", "envsubst '\\${NGINX_PORT} \\${BACKENDPORT} \\${DEFAULT} \\${DOCKER_KEY} \\${DOCKER_CHAIN} \\${HOST} \\${PASSWORD}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"]
    depends_on:
      - test
      - deploy

volumes:
  test-volumes:    
  deploy-volumes: