const commonEnv = {
  HOST:process.env.HOST,
  PORT:process.env.PORT,        
  NAME:process.env.NAME,
  PASSWORD:process.env.PASSWORD,  
  REDISHOST:process.env.REDISHOST,
  REDISPORT:process.env.REDISPORT,       
  ANDROIDID:process.env.ANDROIDID,
  IOSID:process.env.IOSID,
  ANDROIDKEY:process.env.ANDROIDKEY,
  IOSKEY:process.env.IOSKEY,
  ANDROIDEMAIL:process.env.ANDROIDEMAIL,
  IOSEMAIL:process.env.IOSEMAIL,
  NAVER_ACCESSKEY:process.env.NAVER_ACCESSKEY,
  NAVER_SECRETKEY:process.env.NAVER_SECRETKEY,
  NAVER_SERVICEID:process.env.NAVER_SERVICEID,
  COMPANYNUMBER:process.env.COMPANYNUMBER,
  MANAGER:process.env.MANAGER,
  ID:process.env.ID,
  MONGODB_URL:process.env.MONGODB_URL,
  GOOGLEPATH:process.env.GOOGLEPATH,
  APPURL:process.env.APPURL,
  GOOGLECLIENTID:process.env.GOOGLECLIENTID,
  GOOGLESECRETKEY:process.env.GOOGLESECRETKEY,
  DOCKER_KEY:process.env.DOCKER_KEY,
  DOCKER_CERT:process.env.DOCKER_CERT,
  DOCKER_CHAIN:process.env.DOCKER_CHAIN,
  DOCKER_LETSENCRYPT_PATH:process.env.DOCKER_LETSENCRYPT_PATH,
  SESSION_SECRET:process.env.SESSION_SECRET,
  JWT_SECRET:process.env.JWT_SECRET,
  JWT_EXPIRES_IN:process.env.JWT_EXPIRES_IN,
  SMTP_HOST:process.env.SMTP_HOST,
  SMTP_PORT:process.env.SMTP_PORT,
  SMTP_USER:process.env.SMTP_USER,
  SMTP_PASS:process.env.SMTP_PASS,
}

module.exports = {
    apps : [{
      name: "mslBackendTest",
      script: "./dist/main.js",
      args: "start:custom",
      instances: 1,
      autorestart: true,
      watch: false,
      // max_memory_restart: "1G",
      env: {
        NODE_ENV: "development",
        BACKENDPORT:process.env.BACKENDPORT,     
        DATABASE:process.env.DATABASE,
        REDISDB:process.env.REDISDB,  
        MONGO:process.env.MONGO, 
        GOOGLECALLBACKURL:process.env.GOOGLECALLBACKURL,
        GOOGLELOGINURL:process.env.GOOGLELOGINURL,
        EMAILURL:process.env.EMAILURL,
        EMAILSOCKET_URL:process.env.EMAILSOCKET_URL,
        WEB_404URL:process.env.WEB_404URL,
        CHECK_EMAIL:process.env.CHECK_EMAIL,
        ...commonEnv
      },
      env_production: {
        NODE_ENV: "production",
        BACKENDPORT:process.env.DEFAULT,
        DATABASE:process.env.TDATABASE,
        REDISDB:process.env.TREDISDB,
        MONGO:process.env.MONGO_TEST,
        GOOGLECALLBACKURL:process.env.GOOGLECALLBACKURLTEST,
        GOOGLELOGINURL:process.env.GOOGLELOGINURLTEST,
        EMAILURL:process.env.EMAILURL_TEST,
        EMAILSOCKET_URL:process.env.EMAILSOCKET_URL_TEST,
        WEB_404URL:process.env.WEB_404URL_TEST,
        CHECK_EMAIL:process.env.CHECK_EMAIL_TEST,
        ...commonEnv
    }
    }]
  };